### ISSUE TITLE
test

### ISSUE THREAD

**Issue by ChristophWurst** [GretaD/dummy-repository#21]
### Task list

bonjour

### List of the affected Apps

- [X] Calendar
- [X] Calendar Resource Management
- [X] Contacts
- [ ] Mail
- [ ] cdav-library
- [ ] nextcloud/calendar-availability-vue
- [ ] nextcloud/calendar-js
